//! Static content extracted from the Python game at commit 9b02494.
//!
//! `data/content.json` is generated by `tools/extract_content.py`. The sim
//! reads it with `include_str` so the crate has no runtime data-file dependency.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct GoodDef {
    pub id: String,
    pub name: String,
    pub category: String,
    pub base_price: i64,
    pub weight_per_unit: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct MarketSlotDef {
    pub good_id: String,
    pub stock_current: i64,
    pub stock_target: i64,
    pub restock_rate: f64,
    pub local_affinity: f64,
    pub spread: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PortDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub region: String,
    pub features: Vec<String>,
    pub market: Vec<MarketSlotDef>,
    pub port_fee: i64,
    pub provision_cost: i64,
    pub repair_cost: i64,
    pub crew_cost: i64,
    pub map_x: i64,
    pub map_y: i64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ShipDef {
    pub id: String,
    pub name: String,
    pub ship_class: String,
    pub cargo_capacity: i64,
    pub speed: f64,
    pub hull_max: i64,
    pub crew_min: i64,
    pub crew_max: i64,
    pub price: i64,
    pub daily_wage: i64,
    pub storm_resist: f64,
    pub cannons: i64,
    pub maneuver: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RouteDef {
    pub port_a: String,
    pub port_b: String,
    pub distance: i64,
    pub danger: f64,
    pub min_ship_class: String,
    pub lore_name: String,
    pub lore: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PricingDef {
    pub buy_price_mult: f64,
    pub sell_price_mult: f64,
    pub luxury_sell_bonus: f64,
    pub port_fee_mult: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct VoyageModsDef {
    pub provision_burn: f64,
    pub speed_bonus: f64,
    pub storm_resist_bonus: f64,
    pub cargo_damage_mult: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct InspectionDef {
    pub inspection_chance_mult: f64,
    pub seizure_risk: f64,
    pub fine_mult: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ReputationDef {
    pub commercial_trust: i64,
    pub customs_heat: i64,
    pub mediterranean: i64,
    pub north_atlantic: i64,
    pub west_africa: i64,
    pub east_indies: i64,
    pub south_seas: i64,
    pub underworld: BTreeMap<String, i64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CaptainDef {
    pub id: String,
    pub name: String,
    pub title: String,
    pub home_region: String,
    pub home_port_id: String,
    /// NPC who mentored this archetype. Empty when the template has none.
    #[serde(default)]
    pub mentor_npc_id: String,
    pub starting_silver: i64,
    pub starting_ship_id: String,
    pub starting_provisions: i64,
    pub pricing: PricingDef,
    pub voyage: VoyageModsDef,
    pub inspection: InspectionDef,
    pub reputation: ReputationDef,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SeasonDef {
    pub season: String,
    pub region: String,
    pub danger_mult: f64,
    pub speed_mult: f64,
    pub market_effects: BTreeMap<String, f64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FactionDef {
    pub id: String,
    pub name: String,
    pub territory_regions: Vec<String>,
    /// Friendly / neutral / hostile / business / cooperative / respectful.
    /// Missing on older extracts means no smuggler bonus.
    #[serde(default)]
    pub smuggler_attitude: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ArmorDef {
    pub id: String,
    pub name: String,
    pub armor_type: String,
    pub damage_reduction: i64,
    pub dodge_penalty: i64,
    pub stamina_penalty: i64,
    pub silver_cost: i64,
    pub available_regions: Vec<String>,
    pub description: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct MeleeWeaponDef {
    pub id: String,
    pub name: String,
    pub weapon_class: String,
    pub damage_bonus: i64,
    pub thrust_bonus: i64,
    pub slash_bonus: i64,
    pub silver_cost: i64,
    pub available_regions: Vec<String>,
    pub description: String,
    #[serde(default)]
    pub compatible_styles: Vec<String>,
    #[serde(default)]
    pub speed_mod: i64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RangedWeaponDef {
    pub id: String,
    pub name: String,
    pub weapon_type: String,
    pub damage_min: i64,
    pub damage_max: i64,
    pub accuracy: f64,
    pub reload_turns: i64,
    pub silver_cost: i64,
    pub ammo_per_purchase: i64,
    pub available_regions: Vec<String>,
    pub description: String,
    #[serde(default)]
    pub stun_turns: i64,
    #[serde(default)]
    pub loud: bool,
}

#[derive(Debug, Clone, Deserialize)]
pub struct StyleActionDef {
    pub id: String,
    pub name: String,
    pub action_type: String,
    pub stamina_cost: i64,
    pub beats: Vec<String>,
    pub loses_to: Vec<String>,
    pub damage_bonus: i64,
    pub flavor: String,
    pub cooldown: i64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FightingStyleDef {
    pub id: String,
    pub name: String,
    pub region: String,
    pub description: String,
    pub historical_note: String,
    pub passive_thrust_bonus: i64,
    pub passive_slash_bonus: i64,
    pub passive_parry_bonus: i64,
    pub passive_hp_bonus: i64,
    pub passive_dodge_counter: i64,
    pub passive_ranged_accuracy: f64,
    pub passive_injury_bonus: f64,
    pub special_action: Option<StyleActionDef>,
    pub training_port_ids: Vec<String>,
    pub silver_cost: i64,
    pub training_days: i64,
    pub prerequisite_styles: i64,
    pub required_body_parts: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PirateCaptainDef {
    pub id: String,
    pub name: String,
    pub faction_id: String,
    pub personality: String,
    pub strength: i64,
}

/// One row of `content/contracts.py` `TEMPLATES`. Runtime offers are [`crate::model::Contract`].
#[derive(Debug, Clone, Deserialize)]
pub struct ContractDef {
    pub id: String,
    pub family: String,
    pub title_pattern: String,
    pub description: String,
    pub goods_pool: Vec<String>,
    pub quantity_min: i64,
    pub quantity_max: i64,
    pub reward_per_unit: i64,
    pub bonus_reward: i64,
    pub deadline_days: i64,
    pub trust_requirement: String,
    pub standing_requirement: i64,
    pub heat_ceiling: Option<i64>,
    pub inspection_modifier: f64,
    pub source_region: Option<String>,
    pub source_port: Option<String>,
    pub destination_regions: Vec<String>,
    pub captain_bias: Vec<String>,
    pub tags: Vec<String>,
    pub cultural_flavor: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SkillLevelDef {
    pub level: i64,
    pub name: String,
    pub silver_cost: i64,
    pub training_days: i64,
    pub description: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SkillDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub training_port_feature: String,
    pub max_level: i64,
    pub levels: Vec<SkillLevelDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SkillTrainerDef {
    pub id: String,
    pub name: String,
    pub skill_id: String,
    pub port_id: String,
    pub max_teach_level: i64,
    pub description: String,
    pub dialog: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct BlacksmithEffectDef {
    pub level: i64,
    pub maintenance_discount: f64,
    pub degrade_slow: f64,
    pub upgrade_discount: f64,
    pub field_repair: bool,
    pub field_max_quality: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SkillCatalog {
    pub skills: Vec<SkillDef>,
    pub trainers: Vec<SkillTrainerDef>,
    pub blacksmith_effects: Vec<BlacksmithEffectDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CompanionRoleDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub combat_damage_bonus: i64,
    pub combat_interception_chance: f64,
    pub speed_bonus: f64,
    pub danger_reduction: f64,
    pub heal_rate_bonus: f64,
    pub inspection_evasion: f64,
    pub trade_bonus: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CompanionDef {
    pub id: String,
    pub name: String,
    pub role_id: String,
    pub home_port_id: String,
    pub region: String,
    pub description: String,
    pub personality: String,
    pub hire_cost: i64,
    pub required_standing: i64,
    pub greeting: String,
    pub hire_dialog: String,
    pub loyalty_line: String,
    pub warning_line: String,
    pub departure_line: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct MoraleReactionDef {
    pub trigger: String,
    pub deltas: BTreeMap<String, i64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PersonalityModDef {
    pub personality: String,
    pub deltas: BTreeMap<String, i64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CompanionCatalog {
    pub roles: Vec<CompanionRoleDef>,
    pub companions: Vec<CompanionDef>,
    pub morale_reactions: Vec<MoraleReactionDef>,
    pub personality_modifiers: Vec<PersonalityModDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct MerchantDef {
    pub id: String,
    pub name: String,
    pub port_id: String,
    pub title: String,
    pub personality: String,
    pub description: String,
    pub greeting: String,
    pub inventory_types: Vec<String>,
    pub price_markup: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OfficerNamePool {
    pub region: String,
    pub names: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OfficerNames {
    pub regions: Vec<OfficerNamePool>,
    pub traits: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct StyleMasterDef {
    pub id: String,
    pub name: String,
    pub style_id: String,
    pub port_id: String,
    pub description: String,
    pub dialog: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct MilestoneSpecDef {
    pub id: String,
    pub name: String,
    pub family: String,
    pub description: String,
    pub evaluator: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ProfileFamilyDef {
    pub tag: String,
    pub families: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CampaignCatalog {
    pub milestones: Vec<MilestoneSpecDef>,
    pub profile_milestone_families: Vec<ProfileFamilyDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct WarehouseTierDef {
    pub tier: String,
    pub name: String,
    pub capacity: i64,
    pub lease_cost: i64,
    pub upkeep_per_day: i64,
    pub description: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct BrokerOfficeDef {
    pub region: String,
    pub tier: String,
    pub name: String,
    pub purchase_cost: i64,
    pub upkeep_per_day: i64,
    pub board_quality_bonus: f64,
    pub market_signal_bonus: f64,
    pub trade_term_modifier: f64,
    pub description: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct LicenseDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub region_scope: Option<String>,
    pub purchase_cost: i64,
    pub upkeep_per_day: i64,
    pub required_trust_tier: String,
    pub required_standing: i64,
    pub required_heat_max: Option<i64>,
    pub required_broker_tier: Option<String>,
    pub effects: BTreeMap<String, f64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PolicyDef {
    pub id: String,
    pub family: String,
    pub name: String,
    pub description: String,
    pub premium: i64,
    pub coverage_pct: f64,
    pub coverage_cap: i64,
    pub scope: String,
    pub covered_risks: Vec<String>,
    pub exclusions: Vec<String>,
    pub heat_max: Option<i64>,
    pub heat_premium_mult: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CreditTierDef {
    pub tier: String,
    pub name: String,
    pub credit_limit: i64,
    pub interest_rate: f64,
    pub interest_period: i64,
    pub required_trust_tier: String,
    pub required_standing: i64,
    pub required_heat_max: Option<i64>,
    pub required_license: Option<String>,
    pub description: String,
}

/// Catalog from `content/infrastructure.py`: warehouses, brokers, licenses,
/// insurance policies, and credit tiers.
#[derive(Debug, Clone, Deserialize)]
pub struct InfrastructureDef {
    pub warehouse_tiers: Vec<WarehouseTierDef>,
    pub port_warehouse_tiers: BTreeMap<String, Vec<String>>,
    pub brokers: Vec<BrokerOfficeDef>,
    pub licenses: Vec<LicenseDef>,
    pub policies: Vec<PolicyDef>,
    pub credit_tiers: Vec<CreditTierDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct InstitutionSiteDef {
    pub id: String,
    pub name: String,
    pub port_id: String,
    pub institution_type: String,
    pub description: String,
    pub function: String,
    pub political_leaning: String,
    pub npc_id: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PortNpcDef {
    pub id: String,
    pub name: String,
    pub title: String,
    pub port_id: String,
    pub institution: String,
    pub personality: String,
    pub description: String,
    pub agenda: String,
    pub greeting_neutral: String,
    pub greeting_friendly: String,
    pub greeting_hostile: String,
    pub rumor: String,
    pub relationship_notes: BTreeMap<String, String>,
}

/// One port's institutions and NPCs (`PortInstitutionalProfile`).
#[derive(Debug, Clone, Deserialize)]
pub struct PortInstitutionDef {
    pub port_id: String,
    pub governor_title: String,
    pub power_structure: String,
    pub internal_tension: String,
    pub institutions: Vec<InstitutionSiteDef>,
    pub npcs: Vec<PortNpcDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FestivalDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub region: String,
    pub frequency_days: i64,
    pub market_effects: BTreeMap<String, f64>,
    pub duration_days: i64,
    pub standing_bonus: i64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RegionCultureDef {
    pub id: String,
    pub region_name: String,
    pub cultural_name: String,
    pub ethos: String,
    pub trade_philosophy: String,
    pub sacred_goods: Vec<String>,
    pub forbidden_goods: Vec<String>,
    pub prized_goods: Vec<String>,
    pub greeting: String,
    pub farewell: String,
    pub proverb: String,
    pub weather_flavor: Vec<String>,
    pub festivals: Vec<FestivalDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PortCultureDef {
    pub port_id: String,
    pub landmark: String,
    pub local_custom: String,
    pub atmosphere: String,
    pub dock_scene: String,
    pub tavern_rumor: String,
    pub cultural_group: String,
    pub cultural_group_description: String,
}

/// Region cultures and per-port cultural flavor (`content/culture.py`).
#[derive(Debug, Clone, Deserialize, Default)]
pub struct CultureDef {
    #[serde(default)]
    pub regions: Vec<RegionCultureDef>,
    #[serde(default)]
    pub ports: Vec<PortCultureDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SeaEncounterDef {
    pub text: String,
    pub category: String,
    #[serde(default)]
    pub mechanical_effect: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SeaEncounterTableDef {
    pub route_key: String,
    pub encounters: Vec<SeaEncounterDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NpcSightingDef {
    pub npc_name: String,
    pub port_id: String,
    pub region: String,
    pub text: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct WeatherNarrativeDef {
    pub region: String,
    pub season: String,
    pub departure_text: String,
    pub mid_voyage_texts: Vec<String>,
    pub arrival_text: String,
    pub night_text: String,
    pub crew_weather_reaction: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SeaSuperstitionDef {
    pub id: String,
    pub trigger: String,
    pub text: String,
    pub crew_reaction: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CrewMoodDef {
    pub id: String,
    pub condition: String,
    pub flavor_texts: Vec<String>,
}

/// Route flavor, sightings, weather, and crew voice (`content/sea_culture.py`).
#[derive(Debug, Clone, Deserialize, Default)]
pub struct SeaCultureDef {
    #[serde(default)]
    pub route_encounters: Vec<SeaEncounterTableDef>,
    #[serde(default)]
    pub region_encounters: Vec<SeaEncounterTableDef>,
    #[serde(default)]
    pub npc_sightings: Vec<NpcSightingDef>,
    #[serde(default)]
    pub weather: Vec<WeatherNarrativeDef>,
    #[serde(default)]
    pub superstitions: Vec<SeaSuperstitionDef>,
    #[serde(default)]
    pub crew_moods: Vec<CrewMoodDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct TradeBlocDef {
    pub id: String,
    pub name: String,
    pub port_ids: Vec<String>,
    pub description: String,
    pub trade_philosophy: String,
    pub preferred_partners: Vec<String>,
    pub rivals: Vec<String>,
    pub hostile_to: Vec<String>,
    pub loyalty_bonus: f64,
    pub disloyalty_penalty: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PortPoliticalProfileDef {
    pub port_id: String,
    pub bloc_id: String,
    pub local_rival_port: Option<String>,
    pub rivalry_reason: String,
    pub trade_embargo: Vec<String>,
    pub political_flavor: String,
    pub port_grudge: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct BlocRelationshipDef {
    pub bloc_a: String,
    pub bloc_b: String,
    pub disposition: String,
    pub description: String,
    pub spillover: f64,
}

/// Trade blocs and per-port politics (`content/port_politics.py`).
#[derive(Debug, Clone, Deserialize, Default)]
pub struct PortPoliticsDef {
    #[serde(default)]
    pub blocs: Vec<TradeBlocDef>,
    #[serde(default)]
    pub ports: Vec<PortPoliticalProfileDef>,
    #[serde(default)]
    pub relationships: Vec<BlocRelationshipDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FactionRelationshipDef {
    pub faction_a: String,
    pub faction_b: String,
    pub disposition: String,
    pub description: String,
    pub spillover: f64,
    pub vendetta_trigger: String,
}

/// One cross-port NPC relationship.
#[derive(Debug, Clone, Deserialize)]
pub struct CrossPortNetworkDef {
    pub npc_a_id: String,
    pub npc_a_name: String,
    pub npc_a_port: String,
    pub npc_b_id: String,
    pub npc_b_name: String,
    pub npc_b_port: String,
    pub network: String,
    pub disposition: String,
    pub description: String,
    pub player_impact: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct UpgradeDef {
    pub id: String,
    pub name: String,
    pub category: String,
    pub price: i64,
    pub speed_bonus: f64,
    pub hull_max_bonus: i64,
    pub cargo_bonus: i64,
    pub cannon_bonus: i64,
    pub maneuver_bonus: f64,
    pub storm_resist_bonus: f64,
    pub crew_max_bonus: i64,
    pub speed_penalty: f64,
    pub special: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct InjuryDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub severity: String,
    pub body_part: String,
    pub melee_damage_mod: i64,
    pub stamina_max_mod: i64,
    pub hp_max_mod: i64,
    pub ranged_accuracy_mod: f64,
    pub can_dodge: bool,
    pub can_use_firearms: bool,
    pub thrust_multiplier: f64,
    pub heal_days: Option<i64>,
    pub heal_silver: i64,
    pub blocked_body_parts: Vec<String>,
    pub attack_types: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct LootEntryDef {
    pub item_type: String,
    pub item_id: String,
    pub quantity_min: i64,
    pub quantity_max: i64,
    pub weight: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct LootTableDef {
    pub id: String,
    pub entries: Vec<LootEntryDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct AmmoDef {
    pub id: String,
    pub name: String,
    pub weapon_type: String,
    pub silver_cost: i64,
    pub quantity: i64,
    pub available_regions: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Content {
    pub source_commit: String,
    pub goods: Vec<GoodDef>,
    pub ships: Vec<ShipDef>,
    pub ports: Vec<PortDef>,
    pub routes: Vec<RouteDef>,
    pub captains: Vec<CaptainDef>,
    pub seasons: Vec<SeasonDef>,
    pub factions: Vec<FactionDef>,
    pub pirate_captains: Vec<PirateCaptainDef>,
    pub contracts: Vec<ContractDef>,
    #[serde(default)]
    pub armor: Vec<ArmorDef>,
    #[serde(default)]
    pub melee_weapons: Vec<MeleeWeaponDef>,
    #[serde(default)]
    pub ranged_weapons: Vec<RangedWeaponDef>,
    #[serde(default)]
    pub fighting_styles: Vec<FightingStyleDef>,
    pub skills: SkillCatalog,
    pub companions: CompanionCatalog,
    pub merchants: Vec<MerchantDef>,
    pub officer_names: OfficerNames,
    pub style_masters: Vec<StyleMasterDef>,
    pub campaign: CampaignCatalog,
    pub infrastructure: InfrastructureDef,
    pub port_institutions: Vec<PortInstitutionDef>,
    pub port_institutions_east: Vec<PortInstitutionDef>,
    pub cross_port_networks: Vec<CrossPortNetworkDef>,
    #[serde(default)]
    pub culture: CultureDef,
    #[serde(default)]
    pub sea_culture: SeaCultureDef,
    #[serde(default)]
    pub port_politics: PortPoliticsDef,
    #[serde(default)]
    pub faction_relationships: Vec<FactionRelationshipDef>,
    #[serde(default)]
    pub upgrades: Vec<UpgradeDef>,
    #[serde(default)]
    pub injuries: Vec<InjuryDef>,
    #[serde(default)]
    pub loot_tables: Vec<LootTableDef>,
    #[serde(default)]
    pub captain_loot: Vec<LootTableDef>,
    #[serde(default)]
    pub ammo: Vec<AmmoDef>,
}

pub const REGIONS: [&str; 5] = [
    "Mediterranean",
    "North Atlantic",
    "West Africa",
    "East Indies",
    "South Seas",
];

pub fn content() -> &'static Content {
    static CONTENT: OnceLock<Content> = OnceLock::new();
    CONTENT.get_or_init(|| {
        serde_json::from_str(include_str!("../data/content.json"))
            .expect("embedded Portlight content JSON")
    })
}

impl Content {
    pub fn good(&self, id: &str) -> Option<&GoodDef> {
        self.goods.iter().find(|g| g.id == id)
    }

    pub fn ship(&self, id: &str) -> Option<&ShipDef> {
        self.ships.iter().find(|s| s.id == id)
    }

    pub fn captain(&self, id: &str) -> Option<&CaptainDef> {
        self.captains.iter().find(|c| c.id == id)
    }

    pub fn port(&self, id: &str) -> Option<&PortDef> {
        self.ports.iter().find(|p| p.id == id)
    }

    pub fn season_profile(&self, region: &str, day: i64) -> Option<&SeasonDef> {
        let season = season_name(day);
        self.seasons
            .iter()
            .find(|s| s.region == region && s.season == season)
    }

    pub fn factions_in(&self, region: &str) -> Vec<&FactionDef> {
        self.factions
            .iter()
            .filter(|f| f.territory_regions.iter().any(|r| r == region))
            .collect()
    }

    pub fn captains_in_faction(&self, faction_id: &str) -> Vec<&PirateCaptainDef> {
        self.pirate_captains
            .iter()
            .filter(|c| c.faction_id == faction_id)
            .collect()
    }

    pub fn pirate(&self, id: &str) -> Option<&PirateCaptainDef> {
        self.pirate_captains.iter().find(|c| c.id == id)
    }

    pub fn faction(&self, id: &str) -> Option<&FactionDef> {
        self.factions.iter().find(|f| f.id == id)
    }

    pub fn armor(&self, id: &str) -> Option<&ArmorDef> {
        self.armor.iter().find(|a| a.id == id)
    }

    pub fn melee_weapon(&self, id: &str) -> Option<&MeleeWeaponDef> {
        self.melee_weapons.iter().find(|w| w.id == id)
    }

    pub fn ranged_weapon(&self, id: &str) -> Option<&RangedWeaponDef> {
        self.ranged_weapons.iter().find(|w| w.id == id)
    }

    pub fn fighting_style(&self, id: &str) -> Option<&FightingStyleDef> {
        self.fighting_styles.iter().find(|s| s.id == id)
    }

    pub fn skill(&self, id: &str) -> Option<&SkillDef> {
        self.skills.skills.iter().find(|skill| skill.id == id)
    }

    pub fn skill_by_name(&self, name: &str) -> Option<&SkillDef> {
        let name = name.to_lowercase();
        self.skills
            .skills
            .iter()
            .find(|skill| skill.name.to_lowercase() == name)
    }

    /// Trainers at `port_id`, in catalog order. `skill_id` filters further.
    pub fn trainers_at(&self, port_id: &str, skill_id: Option<&str>) -> Vec<&SkillTrainerDef> {
        self.skills
            .trainers
            .iter()
            .filter(|trainer| trainer.port_id == port_id)
            .filter(|trainer| skill_id.is_none_or(|id| trainer.skill_id == id))
            .collect()
    }

    pub fn blacksmith_effect(&self, level: i64) -> &BlacksmithEffectDef {
        let key = level.min(3);
        self.skills
            .blacksmith_effects
            .iter()
            .find(|effect| effect.level == key)
            .or_else(|| {
                self.skills
                    .blacksmith_effects
                    .iter()
                    .find(|effect| effect.level == 0)
            })
            .expect("blacksmith effects")
    }

    pub fn companion(&self, id: &str) -> Option<&CompanionDef> {
        self.companions
            .companions
            .iter()
            .find(|companion| companion.id == id)
    }

    pub fn companion_role(&self, id: &str) -> Option<&CompanionRoleDef> {
        self.companions.roles.iter().find(|role| role.id == id)
    }

    pub fn morale_reaction(&self, trigger: &str) -> Option<&MoraleReactionDef> {
        self.companions
            .morale_reactions
            .iter()
            .find(|row| row.trigger == trigger)
    }

    pub fn personality_modifier(&self, personality: &str) -> Option<&PersonalityModDef> {
        self.companions
            .personality_modifiers
            .iter()
            .find(|row| row.personality == personality)
    }

    pub fn merchant(&self, id: &str) -> Option<&MerchantDef> {
        self.merchants.iter().find(|merchant| merchant.id == id)
    }

    pub fn merchants_at(&self, port_id: &str) -> Vec<&MerchantDef> {
        self.merchants
            .iter()
            .filter(|merchant| merchant.port_id == port_id)
            .collect()
    }

    /// Region name pool. Unknown regions use the Mediterranean list, matching
    /// `generate_officer_name`.
    pub fn officer_pool(&self, region: &str) -> &[String] {
        self.officer_names
            .regions
            .iter()
            .find(|pool| pool.region == region)
            .or_else(|| self.officer_names.regions.first())
            .map(|pool| pool.names.as_slice())
            .unwrap_or(&[])
    }

    pub fn styles_at(&self, port_id: &str) -> Vec<&FightingStyleDef> {
        self.fighting_styles
            .iter()
            .filter(|style| style.training_port_ids.iter().any(|id| id == port_id))
            .collect()
    }

    pub fn masters_at(&self, port_id: &str) -> Vec<&StyleMasterDef> {
        self.style_masters
            .iter()
            .filter(|master| master.port_id == port_id)
            .collect()
    }

    pub fn milestone(&self, id: &str) -> Option<&MilestoneSpecDef> {
        self.campaign.milestones.iter().find(|spec| spec.id == id)
    }

    pub fn warehouse_tier(&self, tier: &str) -> Option<&WarehouseTierDef> {
        self.infrastructure
            .warehouse_tiers
            .iter()
            .find(|spec| spec.tier == tier)
    }

    pub fn port_warehouse_tiers(&self, port_id: &str) -> &[String] {
        self.infrastructure
            .port_warehouse_tiers
            .get(port_id)
            .map(Vec::as_slice)
            .unwrap_or(&[])
    }

    pub fn broker(&self, region: &str, tier: &str) -> Option<&BrokerOfficeDef> {
        self.infrastructure
            .brokers
            .iter()
            .find(|spec| spec.region == region && spec.tier == tier)
    }

    pub fn license(&self, id: &str) -> Option<&LicenseDef> {
        self.infrastructure
            .licenses
            .iter()
            .find(|spec| spec.id == id)
    }

    pub fn policy(&self, id: &str) -> Option<&PolicyDef> {
        self.infrastructure
            .policies
            .iter()
            .find(|spec| spec.id == id)
    }

    pub fn credit_tier(&self, tier: &str) -> Option<&CreditTierDef> {
        self.infrastructure
            .credit_tiers
            .iter()
            .find(|spec| spec.tier == tier)
    }

    pub fn port_institution(&self, port_id: &str) -> Option<&PortInstitutionDef> {
        self.port_institutions
            .iter()
            .chain(self.port_institutions_east.iter())
            .find(|profile| profile.port_id == port_id)
    }

    pub fn npc(&self, id: &str) -> Option<&PortNpcDef> {
        self.port_institutions
            .iter()
            .chain(self.port_institutions_east.iter())
            .flat_map(|profile| profile.npcs.iter())
            .find(|npc| npc.id == id)
    }

    pub fn upgrade(&self, id: &str) -> Option<&UpgradeDef> {
        self.upgrades.iter().find(|u| u.id == id)
    }

    pub fn injury(&self, id: &str) -> Option<&InjuryDef> {
        self.injuries.iter().find(|inj| inj.id == id)
    }

    pub fn loot_table(&self, id: &str) -> Option<&LootTableDef> {
        self.loot_tables.iter().find(|table| table.id == id)
    }

    pub fn captain_loot(&self, id: &str) -> Option<&LootTableDef> {
        self.captain_loot.iter().find(|table| table.id == id)
    }

    pub fn ammo(&self, id: &str) -> Option<&AmmoDef> {
        self.ammo.iter().find(|ammo| ammo.id == id)
    }

    pub fn region_culture(&self, region: &str) -> Option<&RegionCultureDef> {
        self.culture
            .regions
            .iter()
            .find(|rc| rc.region_name == region || rc.id == region)
    }

    pub fn port_culture(&self, port_id: &str) -> Option<&PortCultureDef> {
        self.culture.ports.iter().find(|pc| pc.port_id == port_id)
    }

    pub fn route_encounters(&self, lore_name: &str) -> Option<&SeaEncounterTableDef> {
        self.sea_culture
            .route_encounters
            .iter()
            .find(|table| table.route_key == lore_name)
    }

    pub fn region_encounters(&self, region: &str) -> Option<&SeaEncounterTableDef> {
        self.sea_culture
            .region_encounters
            .iter()
            .find(|table| table.route_key == region)
    }

    pub fn npc_sightings(&self, region: &str) -> Vec<&NpcSightingDef> {
        self.sea_culture
            .npc_sightings
            .iter()
            .filter(|sight| sight.region == region)
            .collect()
    }

    pub fn weather_narrative(&self, region: &str, season: &str) -> Option<&WeatherNarrativeDef> {
        self.sea_culture
            .weather
            .iter()
            .find(|row| row.region == region && row.season == season)
    }

    pub fn trade_bloc(&self, id: &str) -> Option<&TradeBlocDef> {
        self.port_politics.blocs.iter().find(|bloc| bloc.id == id)
    }

    pub fn port_politics(&self, port_id: &str) -> Option<&PortPoliticalProfileDef> {
        self.port_politics
            .ports
            .iter()
            .find(|profile| profile.port_id == port_id)
    }

    pub fn bloc_relationship(&self, bloc_a: &str, bloc_b: &str) -> Option<&BlocRelationshipDef> {
        self.port_politics.relationships.iter().find(|rel| {
            (rel.bloc_a == bloc_a && rel.bloc_b == bloc_b)
                || (rel.bloc_a == bloc_b && rel.bloc_b == bloc_a)
        })
    }

    /// Hostile faction ids, in `FACTION_RELATIONSHIPS` order (`get_enemies`).
    pub fn faction_enemies(&self, faction_id: &str) -> Vec<&str> {
        self.faction_relationships
            .iter()
            .filter(|rel| rel.disposition == "hostile")
            .filter_map(|rel| {
                if rel.faction_a == faction_id {
                    Some(rel.faction_b.as_str())
                } else if rel.faction_b == faction_id {
                    Some(rel.faction_a.as_str())
                } else {
                    None
                }
            })
            .collect()
    }

    /// Strength tiers from `get_loot_table_for_strength`.
    pub fn loot_table_for_strength(&self, strength: i64) -> Option<&LootTableDef> {
        let id = if strength >= 9 {
            "loot_boss"
        } else if strength >= 7 {
            "loot_strong"
        } else if strength >= 5 {
            "loot_medium"
        } else {
            "loot_weak"
        };
        self.loot_table(id)
    }
}

pub fn season_name(day: i64) -> &'static str {
    let day_in_year = (day - 1).rem_euclid(360) + 1;
    if day_in_year <= 90 {
        "spring"
    } else if day_in_year <= 180 {
        "summer"
    } else if day_in_year <= 270 {
        "autumn"
    } else {
        "winter"
    }
}

pub fn upgrade_slots(ship_class: &str) -> i64 {
    match ship_class {
        "sloop" => 2,
        "cutter" => 3,
        "brigantine" => 4,
        "galleon" => 5,
        "man_of_war" => 6,
        _ => 2,
    }
}

pub fn ship_class_rank(template_id: &str) -> i64 {
    const ORDER: [&str; 5] = ["sloop", "cutter", "brigantine", "galleon", "man_of_war"];
    for (rank, name) in ORDER.iter().enumerate() {
        if template_id.contains(name) {
            return rank as i64;
        }
    }
    0
}

pub fn class_rank(class_name: &str) -> i64 {
    match class_name {
        "sloop" => 0,
        "cutter" => 1,
        "brigantine" => 2,
        "galleon" => 3,
        "man_of_war" => 4,
        _ => 0,
    }
}
