//! Static content extracted from the Python game at commit 9b02494.
//!
//! `data/content.json` is generated by `tools/extract_content.py`. The sim
//! reads it with `include_str` so the crate has no runtime data-file dependency.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct GoodDef {
    pub id: String,
    pub name: String,
    pub category: String,
    pub base_price: i64,
    pub weight_per_unit: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct MarketSlotDef {
    pub good_id: String,
    pub stock_current: i64,
    pub stock_target: i64,
    pub restock_rate: f64,
    pub local_affinity: f64,
    pub spread: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PortDef {
    pub id: String,
    pub name: String,
    pub description: String,
    pub region: String,
    pub features: Vec<String>,
    pub market: Vec<MarketSlotDef>,
    pub port_fee: i64,
    pub provision_cost: i64,
    pub repair_cost: i64,
    pub crew_cost: i64,
    pub map_x: i64,
    pub map_y: i64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ShipDef {
    pub id: String,
    pub name: String,
    pub ship_class: String,
    pub cargo_capacity: i64,
    pub speed: f64,
    pub hull_max: i64,
    pub crew_min: i64,
    pub crew_max: i64,
    pub price: i64,
    pub daily_wage: i64,
    pub storm_resist: f64,
    pub cannons: i64,
    pub maneuver: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RouteDef {
    pub port_a: String,
    pub port_b: String,
    pub distance: i64,
    pub danger: f64,
    pub min_ship_class: String,
    pub lore_name: String,
    pub lore: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PricingDef {
    pub buy_price_mult: f64,
    pub sell_price_mult: f64,
    pub luxury_sell_bonus: f64,
    pub port_fee_mult: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct VoyageModsDef {
    pub provision_burn: f64,
    pub speed_bonus: f64,
    pub storm_resist_bonus: f64,
    pub cargo_damage_mult: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct InspectionDef {
    pub inspection_chance_mult: f64,
    pub seizure_risk: f64,
    pub fine_mult: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ReputationDef {
    pub commercial_trust: i64,
    pub customs_heat: i64,
    pub mediterranean: i64,
    pub north_atlantic: i64,
    pub west_africa: i64,
    pub east_indies: i64,
    pub south_seas: i64,
    pub underworld: BTreeMap<String, i64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CaptainDef {
    pub id: String,
    pub name: String,
    pub title: String,
    pub home_region: String,
    pub home_port_id: String,
    pub starting_silver: i64,
    pub starting_ship_id: String,
    pub starting_provisions: i64,
    pub pricing: PricingDef,
    pub voyage: VoyageModsDef,
    pub inspection: InspectionDef,
    pub reputation: ReputationDef,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SeasonDef {
    pub season: String,
    pub region: String,
    pub danger_mult: f64,
    pub speed_mult: f64,
    pub market_effects: BTreeMap<String, f64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FactionDef {
    pub id: String,
    pub name: String,
    pub territory_regions: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PirateCaptainDef {
    pub id: String,
    pub name: String,
    pub faction_id: String,
    pub personality: String,
    pub strength: i64,
}

/// One row of `content/contracts.py` `TEMPLATES`. Runtime offers are [`crate::model::Contract`].
#[derive(Debug, Clone, Deserialize)]
pub struct ContractDef {
    pub id: String,
    pub family: String,
    pub title_pattern: String,
    pub description: String,
    pub goods_pool: Vec<String>,
    pub quantity_min: i64,
    pub quantity_max: i64,
    pub reward_per_unit: i64,
    pub bonus_reward: i64,
    pub deadline_days: i64,
    pub trust_requirement: String,
    pub standing_requirement: i64,
    pub heat_ceiling: Option<i64>,
    pub inspection_modifier: f64,
    pub source_region: Option<String>,
    pub source_port: Option<String>,
    pub destination_regions: Vec<String>,
    pub captain_bias: Vec<String>,
    pub tags: Vec<String>,
    pub cultural_flavor: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Content {
    pub source_commit: String,
    pub goods: Vec<GoodDef>,
    pub ships: Vec<ShipDef>,
    pub ports: Vec<PortDef>,
    pub routes: Vec<RouteDef>,
    pub captains: Vec<CaptainDef>,
    pub seasons: Vec<SeasonDef>,
    pub factions: Vec<FactionDef>,
    pub pirate_captains: Vec<PirateCaptainDef>,
    pub contracts: Vec<ContractDef>,
}

pub const REGIONS: [&str; 5] = [
    "Mediterranean",
    "North Atlantic",
    "West Africa",
    "East Indies",
    "South Seas",
];

pub fn content() -> &'static Content {
    static CONTENT: OnceLock<Content> = OnceLock::new();
    CONTENT.get_or_init(|| {
        serde_json::from_str(include_str!("../data/content.json"))
            .expect("embedded Portlight content JSON")
    })
}

impl Content {
    pub fn good(&self, id: &str) -> Option<&GoodDef> {
        self.goods.iter().find(|g| g.id == id)
    }

    pub fn ship(&self, id: &str) -> Option<&ShipDef> {
        self.ships.iter().find(|s| s.id == id)
    }

    pub fn captain(&self, id: &str) -> Option<&CaptainDef> {
        self.captains.iter().find(|c| c.id == id)
    }

    pub fn port(&self, id: &str) -> Option<&PortDef> {
        self.ports.iter().find(|p| p.id == id)
    }

    pub fn season_profile(&self, region: &str, day: i64) -> Option<&SeasonDef> {
        let season = season_name(day);
        self.seasons
            .iter()
            .find(|s| s.region == region && s.season == season)
    }

    pub fn factions_in(&self, region: &str) -> Vec<&FactionDef> {
        self.factions
            .iter()
            .filter(|f| f.territory_regions.iter().any(|r| r == region))
            .collect()
    }

    pub fn captains_in_faction(&self, faction_id: &str) -> Vec<&PirateCaptainDef> {
        self.pirate_captains
            .iter()
            .filter(|c| c.faction_id == faction_id)
            .collect()
    }

    pub fn pirate(&self, id: &str) -> Option<&PirateCaptainDef> {
        self.pirate_captains.iter().find(|c| c.id == id)
    }
}

pub fn season_name(day: i64) -> &'static str {
    let day_in_year = (day - 1).rem_euclid(360) + 1;
    if day_in_year <= 90 {
        "spring"
    } else if day_in_year <= 180 {
        "summer"
    } else if day_in_year <= 270 {
        "autumn"
    } else {
        "winter"
    }
}

pub fn upgrade_slots(ship_class: &str) -> i64 {
    match ship_class {
        "sloop" => 2,
        "cutter" => 3,
        "brigantine" => 4,
        "galleon" => 5,
        "man_of_war" => 6,
        _ => 2,
    }
}

pub fn ship_class_rank(template_id: &str) -> i64 {
    const ORDER: [&str; 5] = ["sloop", "cutter", "brigantine", "galleon", "man_of_war"];
    for (rank, name) in ORDER.iter().enumerate() {
        if template_id.contains(name) {
            return rank as i64;
        }
    }
    0
}

pub fn class_rank(class_name: &str) -> i64 {
    match class_name {
        "sloop" => 0,
        "cutter" => 1,
        "brigantine" => 2,
        "galleon" => 3,
        "man_of_war" => 4,
        _ => 0,
    }
}
